In [1]:
import flwr as fl
import tensorflow as tf

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train[0].shape

(28, 28)

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.04771302,  0.29875898,  0.4253514 ,  0.43652067,  0.4413122 ,
        -0.383514  ,  0.41132987, -0.27308473,  0.12433259,  0.05356005]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07897343, 0.11167396, 0.12674484, 0.12816842, 0.12878402,
        0.05644747, 0.12498008, 0.06303813, 0.09379928, 0.08739033]],
      dtype=float32)

In [6]:
model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

training and evaluation

In [7]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 514us/step - accuracy: 0.1737 - loss: 2.6122
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 461us/step - accuracy: 0.1527 - loss: 2.3038
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 458us/step - accuracy: 0.1772 - loss: 2.3026
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 476us/step - accuracy: 0.1774 - loss: 2.3026
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 458us/step - accuracy: 0.1799 - loss: 2.3025


In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 325us/step - accuracy: 0.2194 - loss: 2.3026


[2.30259108543396, 0.21940000355243683]

In [9]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [10]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.09485662, 0.1053395 , 0.05415763, 0.21868648, 0.11820818,
        0.11154327, 0.11631409, 0.03130669, 0.0075684 , 0.14201926],
       [0.21198799, 0.1610956 , 0.08771171, 0.13404575, 0.05624728,
        0.13630232, 0.09768849, 0.04738084, 0.01953258, 0.04800745],
       [0.10988917, 0.14028671, 0.09017728, 0.10346025, 0.0866541 ,
        0.12242003, 0.08771878, 0.10571649, 0.03941084, 0.11426632],
       [0.24803267, 0.10291984, 0.08169096, 0.15618272, 0.09106778,
        0.10385434, 0.09963905, 0.07659689, 0.00554931, 0.03446643],
       [0.19721216, 0.08976294, 0.06135171, 0.11999541, 0.14703049,
        0.15224276, 0.08046997, 0.04952184, 0.02636598, 0.07604671]],
      dtype=float32)>