In [1]:
import flwr as fl
import tensorflow as tf

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train[0].shape

(28, 28)

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.07905393,  0.13376799, -0.09906556,  0.08463594, -0.708115  ,
        -0.72518885, -0.19968453, -0.5113188 , -0.00971021,  0.5243733 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.11643957, 0.12298796, 0.09744158, 0.11709136, 0.05299531,
        0.05209816, 0.08811422, 0.06452158, 0.10654936, 0.18176085]],
      dtype=float32)

In [6]:
model.compile("adam", "sparse_categorical_crossentropy", metrics=["accuracy"])

training and evaluation

In [7]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 519us/step - accuracy: 0.4312 - loss: 2.6247
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 470us/step - accuracy: 0.3285 - loss: 2.3013
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 469us/step - accuracy: 0.2906 - loss: 2.3025
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 474us/step - accuracy: 0.2387 - loss: 2.3026
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 467us/step - accuracy: 0.2392 - loss: 2.3026


In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 328us/step - accuracy: 0.2987 - loss: 2.3026


[2.30259108543396, 0.2987000048160553]

In [9]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [10]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.13304454, 0.01651918, 0.12070855, 0.02509664, 0.16894954,
        0.1098548 , 0.05132866, 0.19047062, 0.13373809, 0.05028928],
       [0.09709006, 0.0486876 , 0.20446667, 0.0927085 , 0.08399235,
        0.16576219, 0.08789937, 0.01670725, 0.18701272, 0.01567328],
       [0.07172727, 0.11138212, 0.1132649 , 0.04323785, 0.08804408,
        0.16243657, 0.11523759, 0.0806554 , 0.13191357, 0.08210059],
       [0.23479061, 0.025435  , 0.19796294, 0.01671284, 0.10098709,
        0.12377144, 0.05057509, 0.03551343, 0.18825886, 0.02599278],
       [0.09428936, 0.06268492, 0.10580271, 0.02091507, 0.20013344,
        0.08750928, 0.02704133, 0.07093929, 0.21812446, 0.11256011]],
      dtype=float32)>